name: flutter_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  http: ^1.3.0
  dart_frog: ^1.2.0
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.0.17
  google_fonts: ^4.0.3
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.1
  firebase_auth: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # Asegúrate de tener esta línea

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icono.png"  # Ruta del nuevo icono
  adaptive_icon_background: "#ffffff"  # Solo para Android

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
